version: '3'

services:
  apache:
    image: pruebadocker2-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:80"
    volumes:
      - ./index.php:/var/www/html/index.php
      
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  mysql:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql